wooey/urls.py
from __future__ import absolute_import

from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from . import views
from . import settings as wooey_settings

app_name = 'wooey'

wooey_patterns = [
    url(r'^jobs/command$', views.celery_task_command, name='celery_task_command'),

    url(r'^jobs/queue/global/json$', views.global_queue_json, name='global_queue_json'),
    url(r'^jobs/queue/user/json$', views.user_queue_json, name='user_queue_json'),
    url(r'^jobs/results/user/json$', views.user_results_json, name='user_results_json'),

    url(r'^jobs/queue/all/json', views.all_queues_json, name='all_queues_json'),

    url(r'^jobs/queue/global', views.GlobalQueueView.as_view(), name='global_queue'),
    url(r'^jobs/queue/user', views.UserQueueView.as_view(), name='user_queue'),
    url(r'^jobs/results/user', views.UserResultsView.as_view(), name='user_results'),


    url(r'^jobs/(?P<job_id>[0-9\-]+)/$', views.JobView.as_view(), name='celery_results'),
    url(r'^jobs/(?P<job_id>[0-9\-]+)/json$', views.JobJSON.as_view(), name='celery_results_json'),
    url(r'^jobs/(?P<job_id>[0-9\-]+)/jsonhtml$', views.JobJSONHTML.as_view(), name='celery_results_json_html'),

    # Global public access via uuid
    url(r'^jobs/(?P<uuid>[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12})/$', views.JobView.as_view(), name='celery_results_uuid'),
    url(r'^jobs/(?P<uuid>[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12})/json$', views.JobJSON.as_view(), name='celery_results_json_uuid'),


    url(r'^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/$', views.WooeyScriptView.as_view(), name='wooey_script'),
    url(r'^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/version/(?P<script_version>[^/]+)$', views.WooeyScriptView.as_view(), name='wooey_script'),
    url(r'^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/version/(?P<script_version>[^/]+)/iteration/(?P<script_iteration>\d+)$', views.WooeyScriptView.as_view(), name='wooey_script'),
    url(r'^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/version/(?P<script_version>[^/]+)/jobs/(?P<job_id>[a-zA-Z0-9\-]+)$', views.WooeyScriptView.as_view(), name='wooey_script'),
    url(r'^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/version/(?P<script_version>[^/]+)/iteration/(?P<script_iteration>\d+)/jobs/(?P<job_id>[a-zA-Z0-9\-]+)$', views.WooeyScriptView.as_view(), name='wooey_script'),
    url(r'^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/jobs/(?P<job_id>[a-zA-Z0-9\-]+)$', views.WooeyScriptView.as_view(), name='wooey_script_clone'),
    url(r'^scripts/(?P<slug>[a-zA-Z0-9\-\_]+)/$', views.WooeyScriptJSON.as_view(), name='wooey_script_json'),

    url(r'^scripts/search/json$', views.WooeyScriptSearchJSON.as_view(), name='wooey_search_script_json'),
    url(r'^scripts/search/jsonhtml$', views.WooeyScriptSearchJSONHTML.as_view(), name='wooey_search_script_jsonhtml'),


    url(r'^profile/$', views.WooeyProfileView.as_view(), name='profile_home'),
    url(r'^profile/(?P<username>[a-zA-Z0-9\-]+)$', views.WooeyProfileView.as_view(), name='profile'),

    url(r'^$', views.WooeyHomeView.as_view(), name='wooey_home'),
    url(r'^$', views.WooeyHomeView.as_view(), name='wooey_job_launcher'),
    url('^{}'.format(wooey_settings.WOOEY_LOGIN_URL.lstrip('/')), views.wooey_login, name='wooey_login'),

    url(r'^favorite/toggle$', views.toggle_favorite, name='toggle_favorite'),

    url(r'^scrapbook$', views.WooeyScrapbookView.as_view(), name='scrapbook'),


    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),

]

if wooey_settings.WOOEY_REGISTER_URL:
    wooey_patterns += [
        url(r'^{}'.format(wooey_settings.WOOEY_REGISTER_URL.lstrip('/')), views.WooeyRegister.as_view(), name='wooey_register'),
    ]

urlpatterns = [
    url(r'^', include(wooey_patterns)),
]

wooey/forms/scripts.py
from __future__ import absolute_import
from django import forms


class WooeyForm(forms.Form):
    wooey_type = forms.IntegerField(widget=forms.HiddenInput)
    wooey_parser = forms.IntegerField(widget=forms.HiddenInput, required=False)

    def add_wooey_fields(self):
        # This adds fields such as job name, description that we like to validate on but don't want to include in
        # form rendering
        self.fields['job_name'] = forms.CharField()
        self.fields['job_description'] = forms.CharField(required=False)

wooey/templates/wooey/scripts/script_panel.html
{% load i18n %}
{% load wooey_tags %}
{% get_wooey_setting "WOOEY_SHOW_LOCKED_SCRIPTS" as wooey_show_locked_scripts %}
{% if script.is_active or wooey_show_locked_scripts %}
<div class="col-sm-6 col-md-4">

    {% with group_show=script.script_group|valid_user:request.user %}
        {% if group_show != 'hide' %}

        <div class="panel {% if script.id in favorite_script_ids %}panel-warning is-favorite{% else %}panel-default{% endif %} thumbnail wooey_script_thumbnail {% if not script.is_active or group_show == 'disabled' %}wooey_script_disabled {% endif %}"  id="favorite-{{ script|app_model_id }}">
            <div class="panel-heading">

                {% if script.is_active and group_show == True %}
                    <a href="{% url 'wooey:wooey_script' slug=script.slug %}">{{ script.script_name }}</a>
                    {% with previous_versions=script.get_previous_versions %}
                        {% if previous_versions %}
                            <div class="dropdown wooey-script-dropdown">
                                <a href="#" class="dropdown dropdown-toggle" id="{{ script.id }}_scriptDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    {% regroup previous_versions by script_version as script_version_list %}
                                    {% for past_script_versions in script_version_list %}
                                        <li class="dropdown-header">{% blocktrans with version=past_script_versions.grouper %}Version {{ version }}{% endblocktrans %}</li>
                                        {% for past_script in past_script_versions.list %}
                                            <li><a href="{{ past_script.get_version_url }}">
                                                {% blocktrans with iteration=past_script.script_iteration %}Iteration {{ iteration }}{% endblocktrans %}</a>
                                            </li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    {% endwith %}
                {% else %}
                    {{ script.script_name }}
                    <a class="icon icon-locked" href="#" title="This script is unavailable."></a>
                {% endif %}
                <a class="icon icon-favorite requires-login" data-favorite="{{ script|app_model_id }}"  href="#"></a>
            </div>
        <div class="panel-body">{{ script.script_description }}</div>
        <div class="wooey-script-group">{{ script.script_group.group_name }}</div>

        </div>
        {% endif %}
    {% endwith %}
</div>
{% endif %}

wooey/templates/wooey/scripts/scriptgroup_view.html
{% extends "wooey/base.html" %}
{% load i18n %}
{% load wooey_tags %}

{% block center_content %}


{% endblock center_content %}